# Generated by Django 4.2.7 on 2023-11-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_user_customer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
    ]
